**Import Data**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
from google.colab import drive
import gdown
import os

warnings.filterwarnings("ignore")

In [2]:
file_id = '1C0dxQBvT92qE1dVLtnhtbzvM4JHu3sF6'
url = f'https://drive.google.com/uc?id={file_id}'
output_folder = 'data'
output_file = os.path.join(output_folder, 'ML_Project_Raw_Dataset.csv')

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

if not os.path.isfile(output_file):
    print("Fetching dataset from Google Drive...")
    gdown.download(url, output_file, quiet=False)
else:
    print("Dataset already present in /data folder.")

df = pd.read_csv(output_file, encoding='latin1', low_memory=False)
print(f"Successfully loaded {len(df)} rows.")

df.head()

Fetching dataset from Google Drive...

Downloading...
From (original): https://drive.google.com/uc?id=1C0dxQBvT92qE1dVLtnhtbzvM4JHu3sF6
From (redirected): https://drive.google.com/uc?id=1C0dxQBvT92qE1dVLtnhtbzvM4JHu3sF6&confirm=t&uuid=48334745-07e5-4e10-80cf-d05abbabdf87
To: /content/data/ML_Project_Raw_Dataset.csv
100%|██████████| 284M/284M [00:06<00:00, 45.7MB/s]

Successfully loaded 220557 rows.

,sub_property_type,agent_name,living_space,land_space_raw,price_per_unit,price_max,searched_field,bathroom_number,property_status,search_date,...,longitude,property_street_address,land_space_unit,short_description,property_type_searched,property_url,tenure,parking_number,listing_headline,agent_email
0,For Sale,à¸à¸¸à¸à¹à¸à¸§à¹ 095-405-8716,280.0,271.2 sqm,à¸¿84623.8938 / sqm,22950000.0,TH1001_2_1.html,NaN,ACT,NaN,...,100.493890,"Ban Phan Thom, Phra Nakhon, Bangkok",sqm,NaN,For_Sale,https://www.ddproperty.com/en/property/bh-0107...,Freehold,NaN,BH_01075 à¸à¸²à¸¢ à¸à¹à¸²à¸à¹à¸à¸µà¹à¸...,NaN
1,For Sale,Nakornthong Property,NaN,328 sqm,à¸¿48780.4878 / sqm,16000000.0,TH1001_2_1.html,NaN,ACT,NaN,...,100.502005,"Ban Phan Thom, Phra Nakhon, Bangkok",sqm,NaN,For_Sale,https://www.ddproperty.com/en/property/à¸à¸µà...,NaN,NaN,à¸à¸µà¹à¸à¸´à¸à¸à¸£à¹à¸­à¸¡à¸à¹à¸²à¸à...,NaN
2,For Sale,Nakornthong Property,NaN,328 sqm,à¸¿48780.4878 / sqm,16000000.0,TH1001_2_1.html,NaN,ACT,NaN,...,100.501159,"Ban Phan Thom, Phra Nakhon, Bangkok",sqm,NaN,For_Sale,https://www.ddproperty.com/en/property/à¸à¸µà...,Freehold,NaN,à¸à¸µà¹à¸à¸´à¸ à¸à¸£à¹à¸­à¸¡à¸à¹à¸²à¸...,NaN
3,For Sale,Pichai.So,35.0,NaN,à¸¿62857.1429 / sqm,2200000.0,TH1001_2_1.html,1.0,ACT,NaN,...,100.504052,"à¸à¸­à¸¢ à¹à¸à¹à¸§à¸¨à¸£à¹ 1, Bang Khun P...",NaN,NaN,For_Sale,https://www.ddproperty.com/en/property/à¸à¸²à...,Freehold,NaN,à¸à¸²à¸¢à¸à¹à¸§à¸! Condo à¹à¸à¹à¸§à¸¨à¸...,NaN
4,For Sale,Uptown Assets,28.0,NaN,à¸¿53571.4286 / sqm,1500000.0,TH1001_2_1.html,1.0,ACT,NaN,...,100.501765,"1 Dinso Road, Bowon Niwet, Phra Nakhon, Bangkok",NaN,NaN,For_Sale,https://www.ddproperty.com/en/property/for-sal...,NaN,NaN,For Sale Lumpini Ville Ramkhamhang 26 | UA-01786,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220557 entries, 0 to 220556
Data columns (total 69 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   sub_property_type        220557 non-null  object
 1   agent_name               220463 non-null  object
 2   living_space             188470 non-null  float64
 3   land_space_raw           85554 non-null   object
 4   price_per_unit           220557 non-null  object
 5   price_max                220557 non-null  float64
 6   searched_field           220557 non-null  object
 7   bathroom_number          186387 non-null  float64
 8   property_status          220557 non-null  object
 9   search_date              0 non-null       float64
 10  ad_type                  0 non-null       float64
 11  currency                 220557 non-null  object
 12  apartment_number         0 non-null       float64
 13  price_raw                220557 non-null  object
 14  property_type            220557 non-null  object
 15  property_id              220557 non-null  int64
 16  building_name            0 non-null       float64
 17  city                     220557 non-null  object
 18  floor_level              91172 non-null   object
 19  additional_variables     0 non-null       float64
 20  website_searched         220557 non-null  object
 21  furnished                95189 non-null   object
 22  half_bathroom_number     0 non-null       float64
 23  developer_name           110316 non-null  object
 24  price_min                220557 non-null  float64
 25  page_visits              0 non-null       float64
 26  state                    220557 non-null  object
 27  property_name            199665 non-null  object
 28  built_year               107856 non-null  float64
 29  room_number              0 non-null       float64
 30  latitude                 219247 non-null  float64
 31  photos_number            0 non-null       float64
 32  auction_date             0 non-null       float64
 33  reduced_date             0 non-null       float64
 34  videos_number            0 non-null       float64
 35  DATE_SCRAPED             220557 non-null  object
 36  land_space               85554 non-null   float64
 37  RUN_START_DATE           220557 non-null  object
 38  premium                  220557 non-null  int64
 39  description              0 non-null       float64
 40  bedroom_number           186781 non-null  float64
 41  agent_phone              217201 non-null  object
 42  new_home                 0 non-null       float64
 43  commercial               220557 non-null  int64
 44  price                    220557 non-null  float64
 45  added_date               0 non-null       float64
 46  area_code                214817 non-null  object
 47  search_date_id           0 non-null       float64
 48  agent_url                220557 non-null  object
 49  agency_name              220456 non-null  object
 50  agent_id                 220557 non-null  int64
 51  address                  220557 non-null  object
 52  listing_label            220557 non-null  object
 53  living_space_raw         188470 non-null  object
 54  living_space_unit        188470 non-null  object
 55  increased_date           0 non-null       float64
 56  floorplans_number        0 non-null       float64
 57  last_updated             220557 non-null  object
 58  country                  220557 non-null  object
 59  longitude                219247 non-null  float64
 60  property_street_address  220557 non-null  object
 61  land_space_unit          85554 non-null   object
 62  short_description        0 non-null       float64
 63  property_type_searched   220557 non-null  object
 64  property_url             220557 non-null  object
 65  tenure                   126410 non-null  object
 66  parking_number           0 non-null       float64
 67  listing_headline         220557 non-null  object
 68  agent_email              0 non-null       float64
dtypes: float64(31), int64(4), object(34)
memory usage: 116.1+ MB

In [4]:
df.shape

(220557, 69)

**Data Cleaning**

In [5]:
useful_columns = [
    'price',
    'living_space',
    'bedroom_number',
    'bathroom_number',
    'room_number',
    'parking_number',
    'property_type',
    'city',
    'state',
    'built_year',
    'furnished',
    'new_home'
]

df = df[useful_columns].copy()
df = df.drop_duplicates()
df.head()

,price,living_space,bedroom_number,bathroom_number,room_number,parking_number,property_type,city,state,built_year,furnished,new_home
0,22950000.0,280.0,NaN,NaN,NaN,NaN,Detached House,Phra Nakhon,Bangkok,NaN,NaN,NaN
1,16000000.0,NaN,NaN,NaN,NaN,NaN,Land,Phra Nakhon,Bangkok,NaN,NaN,NaN
3,2200000.0,35.0,0.0,1.0,NaN,NaN,Condo,Phra Nakhon,Bangkok,NaN,Partially Furnished,NaN
4,1500000.0,28.0,1.0,1.0,NaN,NaN,Condo,Phra Nakhon,Bangkok,NaN,Fully Furnished,NaN
5,2900000.0,37.0,2.0,1.0,NaN,NaN,Condo,Phra Nakhon,Bangkok,NaN,Fully Furnished,NaN

In [6]:
df.isnull().mean().sort_values(ascending = False)

parking_number     1.000000
new_home           1.000000
room_number        1.000000
furnished          0.565223
built_year         0.526768
bathroom_number    0.144426
bedroom_number     0.141447
living_space       0.138251
price              0.000000
property_type      0.000000
city               0.000000
state              0.000000
dtype: float64

In [7]:
df = df.drop(columns = ['parking_number', 'new_home', 'room_number'])
df = df[df['property_type'] != 'Land']
df = df.dropna(subset=['price'])
df.isnull().mean().sort_values(ascending = False)

furnished          0.514594
built_year         0.472022
bathroom_number    0.044652
bedroom_number     0.041263
living_space       0.037695
price              0.000000
property_type      0.000000
state              0.000000
city               0.000000
dtype: float64

In [8]:
df.head(10)

,price,living_space,bedroom_number,bathroom_number,property_type,city,state,built_year,furnished
0,22950000.0,280.0,NaN,NaN,Detached House,Phra Nakhon,Bangkok,NaN,NaN
3,2200000.0,35.0,0.0,1.0,Condo,Phra Nakhon,Bangkok,NaN,Partially Furnished
4,1500000.0,28.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,NaN,Fully Furnished
5,2900000.0,37.0,2.0,1.0,Condo,Phra Nakhon,Bangkok,NaN,Fully Furnished
6,3000000.0,36.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,NaN,Fully Furnished
7,2000000.0,23.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,NaN,Fully Furnished
16,35000000.0,1000.0,6.0,6.0,Detached House,Phra Nakhon,Bangkok,NaN,Fully Furnished
17,18500000.0,165.0,3.0,2.0,Condo,Phra Nakhon,Bangkok,NaN,NaN
19,169900000.0,NaN,4.0,4.0,Apartment,Phra Nakhon,Bangkok,NaN,NaN
20,20000000.0,220.0,10.0,5.0,Detached House,Phra Nakhon,Bangkok,NaN,Partially Furnished

In [9]:
df.isnull().mean().sort_values(ascending = False)

furnished          0.514594
built_year         0.472022
bathroom_number    0.044652
bedroom_number     0.041263
living_space       0.037695
price              0.000000
property_type      0.000000
state              0.000000
city               0.000000
dtype: float64

In [10]:
df.isnull().sum().sort_values(ascending = False)

furnished          83357
built_year         76461
bathroom_number     7233
bedroom_number      6684
living_space        6106
price                  0
property_type          0
state                  0
city                   0
dtype: int64

In [11]:
df['bathroom_number'] = pd.to_numeric(df['bathroom_number'], errors='coerce')
df['bedroom_number']  = pd.to_numeric(df['bedroom_number'], errors='coerce')
df['living_space']    = pd.to_numeric(df['living_space'], errors='coerce')
df['built_year']      = pd.to_numeric(df['built_year'], errors='coerce')

In [12]:
df['bathroom_number'] = df['bathroom_number'].fillna(df['bathroom_number'].median())
df['bedroom_number']  = df['bedroom_number'].fillna(df['bedroom_number'].median())
df['living_space']    = df['living_space'].fillna(df['living_space'].median())
df = df.dropna(subset=['city', 'state', 'property_type'])

df['built_year']  = df['built_year'].fillna(df['built_year'].median())
df['furnished']   = df['furnished'].fillna('Unknown')
df = df.drop_duplicates()

In [13]:
df.head(10)

,price,living_space,bedroom_number,bathroom_number,property_type,city,state,built_year,furnished
0,22950000.0,280.0,2.0,2.0,Detached House,Phra Nakhon,Bangkok,2014.0,Unknown
3,2200000.0,35.0,0.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Partially Furnished
4,1500000.0,28.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished
5,2900000.0,37.0,2.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished
6,3000000.0,36.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished
7,2000000.0,23.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished
16,35000000.0,1000.0,6.0,6.0,Detached House,Phra Nakhon,Bangkok,2014.0,Fully Furnished
17,18500000.0,165.0,3.0,2.0,Condo,Phra Nakhon,Bangkok,2014.0,Unknown
19,169900000.0,65.5,4.0,4.0,Apartment,Phra Nakhon,Bangkok,2014.0,Unknown
20,20000000.0,220.0,10.0,5.0,Detached House,Phra Nakhon,Bangkok,2014.0,Partially Furnished

In [14]:
df.isnull().sum()

price              0
living_space       0
bedroom_number     0
bathroom_number    0
property_type      0
city               0
state              0
built_year         0
furnished          0
dtype: int64

In [15]:
df.shape

(161433, 9)

**Outlier Detection**

In [16]:
numerical_cols = ['price', 'living_space', 'bedroom_number', 'bathroom_number', 'built_year']
display(df[numerical_cols].describe())

,price,living_space,bedroom_number,bathroom_number,built_year
count,1.614330e+05,1.614330e+05,161433.000000,161433.000000,161433.000000
mean,2.785181e+07,4.127092e+02,2.136218,2.037972,2014.176649
std,4.239686e+09,2.382988e+04,2.563107,1.997405,3.393582
min,0.000000e+00,1.000000e+00,0.000000,0.000000,1971.000000
25%,2.800000e+06,3.500000e+01,1.000000,1.000000,2014.000000
50%,5.250000e+06,6.550000e+01,2.000000,2.000000,2014.000000
75%,1.125000e+07,1.500000e+02,3.000000,2.000000,2015.000000
max,1.650000e+12,6.000000e+06,279.000000,220.000000,2025.000000

In [17]:
df = df[df['price'] > 500_000]
df = df[df['price'] < 100_000_000]

Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 3.0 * IQR
upper_bound = Q3 + 3.0 * IQR

df = df[(df['price'] >= lower_bound) & (df['price'] <= upper_bound)]

print(f"Max price after cleaning: {df['price'].max():,.2f}")

Max price after cleaning: 35,310,000.00

In [18]:
df = df[df['living_space'].between(10, 10000)]

df = df[df['bedroom_number'].between(1, 15)]
df = df[df['bathroom_number'].between(1, 15)]

print(f"Rows remaining after cleanup: {len(df)}")

Rows remaining after cleanup: 141746

In [19]:
numerical_cols = ['price', 'living_space', 'bedroom_number', 'bathroom_number', 'built_year']
display(df[numerical_cols].describe())

,price,living_space,bedroom_number,bathroom_number,built_year
count,1.417460e+05,141746.000000,141746.000000,141746.000000,141746.000000
mean,7.644994e+06,121.229907,2.077731,1.922446,2014.159546
std,6.949315e+06,247.520899,1.236874,1.179027,3.386924
min,5.010000e+05,10.000000,1.000000,1.000000,1971.000000
25%,2.890000e+06,35.470000,1.000000,1.000000,2014.000000
50%,5.100000e+06,65.500000,2.000000,2.000000,2014.000000
75%,9.700000e+06,137.000000,3.000000,2.000000,2015.000000
max,3.531000e+07,10000.000000,15.000000,15.000000,2025.000000

In [20]:
df.shape

(141746, 9)

**Feature Engineering**

In [21]:
df['property_age'] = 2026 - df['built_year']

df['living_space_ratio'] = df['living_space'] / (df['bedroom_number'] + df['bathroom_number'])

df['total_rooms'] = df['bedroom_number'] + df['bathroom_number']

city_means = df.groupby('city')['price'].transform('mean')
df['city_price_index'] = city_means

type_means = df.groupby('property_type')['price'].transform('mean')
df['type_space_interaction'] = type_means * df['living_space']

In [22]:
print("--- All Unique States (Provinces) ---")
states = df['state'].unique()
print(sorted(states))

print("\n--- Top 20 Cities (Districts) ---")
print(df['city'].value_counts().head(20))

print("\n--- Breakdown of Cities in the largest State ---")
top_state = df['state'].value_counts().index[0]
print(f"Top State: {top_state}")
print(df[df['state'] == top_state]['city'].value_counts().head(10))

--- All Unique States (Provinces) ---
['Amnat Charoen', 'Ang Thong', 'Bangkok', 'Buri Ram', 'Chachoengsao', 'Chai Nat', 'Chaiyaphum', 'Chanthaburi', 'Chiang Mai', 'Chiang Rai', 'Chon Buri', 'Chumphon', 'Kalasin', 'Kamphaeng Phet', 'Kanchanaburi', 'Khon Kaen', 'Krabi', 'Lampang', 'Lamphun', 'Loei', 'Lop Buri', 'Mae Hong Son', 'Maha Sarakham', 'Mukdahan', 'Nakhon Nayok', 'Nakhon Pathom', 'Nakhon Phanom', 'Nakhon Ratchasima', 'Nakhon Sawan', 'Nakhon Si Thammarat', 'Nan', 'Narathiwat', 'Nong Bua Lam Phu', 'Nong Khai', 'Nonthaburi', 'Pathum Thani', 'Pattani', 'Pattaya', 'Phangnga', 'Phatthalung', 'Phayao', 'Phetchabun', 'Phetchaburi', 'Phichit', 'Phitsanulok', 'Phra Nakhon Si Ayutthaya', 'Phrae', 'Phuket', 'Prachin Buri', 'Prachuap Khiri Khan', 'Ranong', 'Ratchaburi', 'Rayong', 'Roi Et', 'Sa Kaeo', 'Sakon Nakhon', 'Samut Prakan', 'Samut Sakhon', 'Samut Songkhram', 'Saraburi', 'Si Sa Ket', 'Sing Buri', 'Songkhla', 'Sukhothai', 'Suphan Buri', 'Surat Thani', 'Surin', 'Tak', 'Trang', 'Trat', 'Ubon Ratchathani', 'Udon Thani', 'Uthai Thani', 'Uttaradit', 'Yala', 'Yasothon']

--- Top 20 Cities (Districts) ---
city
Watthana               14091
Khlong Toei             9354
Huai Khwang             7633
Chatuchak               5219
Bang Lamung             4086
Pattaya                 4054
Ratchathewi             3604
Hua Hin                 3569
Phra Khanong            3490
Sathon                  2976
Pathum Wan              2895
Bang Rak                2828
Suan Luang              2745
Muang Nonthaburi        2669
Muang Samut Prakarn     2592
Bang Plee               2519
Yan Nawa                2273
Khlong San              2272
Muang Chiang Mai        2268
Bang Kapi               2268
Name: count, dtype: int64

--- Breakdown of Cities in the largest State ---
Top State: Bangkok
city
Watthana        14091
Khlong Toei      9354
Huai Khwang      7633
Chatuchak        5219
Ratchathewi      3604
Phra Khanong     3490
Sathon           2976
Pathum Wan       2895
Bang Rak         2828
Suan Luang       2745
Name: count, dtype: int64

In [23]:
def get_region(state):
    central = ['Bangkok', 'Nonthaburi', 'Pathum Thani', 'Samut Prakan', 'Samut Sakhon', 'Nakhon Pathom']
    east = ['Chon Buri', 'Rayong', 'Chachoengsao', 'Pattaya']
    north = ['Chiang Mai', 'Chiang Rai', 'Lampang', 'Phuket', 'Krabi'] # Phuket/Krabi are South but often grouped for high-tourism
    if state in central: return 'BKK_Metropolitan'
    if state in east: return 'EEC_Zone'
    if state in ['Phuket', 'Krabi', 'Surat Thani', 'Phangnga']: return 'Southern_Tourist'
    return 'Upcountry'

df['region'] = df['state'].apply(get_region)

df['city'] = df['city'].replace({'Pattaya': 'Bang Lamung'})

bangkok_metro = [
    'Bangkok', 'Krung Thep Maha Nakhon', 'Nonthaburi',
    'Samut Prakan', 'Pathum Thani', 'Samut Sakhon', 'Nakhon Pathom'
]

df['is_bangkok'] = df['state'].apply(lambda x: 1 if x in bangkok_metro else 0)

In [24]:
city_sqm_price = df.groupby('city').apply(lambda x: x['price'].sum() / x['living_space'].sum()).to_dict()
df['city_sqm_baseline'] = df['city'].map(city_sqm_price)

city_avg_size = df.groupby('city')['living_space'].transform('mean')
df['size_vs_city_avg'] = df['living_space'] / city_avg_size

df['space_per_bed'] = df['living_space'] / df['bedroom_number'].replace(0, 1)

df['is_micro_unit'] = (df['living_space'] < 35).astype(int)

In [25]:
df.head()

,price,living_space,bedroom_number,bathroom_number,property_type,city,state,built_year,furnished,property_age,living_space_ratio,total_rooms,city_price_index,type_space_interaction,region,is_bangkok,city_sqm_baseline,size_vs_city_avg,space_per_bed,is_micro_unit
0,22950000.0,280.0,2.0,2.0,Detached House,Phra Nakhon,Bangkok,2014.0,Unknown,12.0,70.000000,4.0,9.096657e+06,2.729098e+09,BKK_Metropolitan,1,68930.390599,2.121714,140.0,0
4,1500000.0,28.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished,12.0,14.000000,2.0,9.096657e+06,2.055481e+08,BKK_Metropolitan,1,68930.390599,0.212171,28.0,1
5,2900000.0,37.0,2.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished,12.0,12.333333,3.0,9.096657e+06,2.716171e+08,BKK_Metropolitan,1,68930.390599,0.280369,18.5,0
6,3000000.0,36.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished,12.0,18.000000,2.0,9.096657e+06,2.642761e+08,BKK_Metropolitan,1,68930.390599,0.272792,36.0,0
7,2000000.0,23.0,1.0,1.0,Condo,Phra Nakhon,Bangkok,2014.0,Fully Furnished,12.0,11.500000,2.0,9.096657e+06,1.688431e+08,BKK_Metropolitan,1,68930.390599,0.174284,23.0,1

In [26]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 4.3 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

**Data Preprocessing**

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import category_encoders as ce
from category_encoders import TargetEncoder
from sklearn.pipeline import Pipeline

In [28]:
x = df.drop(columns=['price'])
y = df['price']

In [29]:
num = [
    'living_space', 'bedroom_number', 'bathroom_number', 'built_year',
    'property_age', 'living_space_ratio', 'total_rooms',
    'city_price_index', 'type_space_interaction',
    'city_sqm_baseline', 'size_vs_city_avg', 'space_per_bed',
]

cat_subset = [
    'property_type',
    'state',
    'furnished',
    'region',
    'is_bangkok'
]

In [30]:
preprocess = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_subset),
        ('city_enc', TargetEncoder(), ['city'])
    ]
)

In [31]:
pipeline_lr = Pipeline(steps=[
    ('preprocess', preprocess),
    ('model', LinearRegression())
])

pipeline_dt = Pipeline(steps=[
    ('preprocessor', preprocess),
    ('regressor', DecisionTreeRegressor(max_depth = 15, min_samples_leaf = 50, random_state = 42
    ))
])

pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocess),
    ('regressor', XGBRegressor(
        objective='count:poisson',
        n_estimators=2500,
        learning_rate=0.02,
        max_depth=10,
        random_state=42
    ))
])

In [32]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size = 0.2,
    random_state = 42,
)

**Linear Regression**

In [33]:
pipeline_lr.fit(x_train, y_train)
pred_lr = pipeline_lr.predict(x_test)

r2_lr = r2_score(y_test, pred_lr)
mae_lr = mean_absolute_error(y_test, pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, pred_lr))

print("--- Linear Regression ---")
print(f"R²:   {r2_lr:.4f}")
print(f"MAE:  {mae_lr:,.2f}")
print(f"RMSE: {rmse_lr:,.2f}")

--- Linear Regression ---
R²:   0.5269
MAE:  3,057,311.14
RMSE: 4,750,043.16

**Decision Tree**

In [34]:
pipeline_dt.fit(x_train, y_train)
pred_rf = pipeline_dt.predict(x_test)

r2_dt = r2_score(y_test, pred_rf)
mae_dt = mean_absolute_error(y_test, pred_rf)
rmse_dt = np.sqrt(mean_squared_error(y_test, pred_rf))

print("--- Decision Tree ---")
print(f"R²:   {r2_dt:.4f}")
print(f"MAE:  {mae_dt:,.2f}")
print(f"RMSE: {rmse_dt:,.2f}")

--- Decision Tree ---
R²:   0.7410
MAE:  2,071,382.75
RMSE: 3,514,375.88

**XGBoost**

In [35]:
pipeline_xgb.fit(x_train, y_train)
pred_xgb = pipeline_xgb.predict(x_test)

r2_xgb = r2_score(y_test, pred_xgb)
mae_xgb = mean_absolute_error(y_test, pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, pred_xgb))

print("--- XGBoost ---")
print(f"R²:   {r2_xgb:.4f}")
print(f"MAE:  {mae_xgb:,.2f}")
print(f"RMSE: {rmse_xgb:,.2f}")

--- XGBoost ---
R²:   0.8006
MAE:  1,754,247.81
RMSE: 3,083,661.78

**Results**

In [36]:
results_df = pd.DataFrame([
    ['Linear Regression', rmse_lr, mae_lr, r2_lr],
    ['Decision Tree', rmse_dt, mae_dt, r2_dt],
    ['XGBoost', rmse_xgb, mae_xgb, r2_xgb],
], columns = ['Model', 'RMSE', 'MAE', 'R²']
)

results_df = results_df.sort_values(by='R²', ascending=False).reset_index(drop=True)

results_df.round(2)

               Model        RMSE         MAE    R²
0            XGBoost  3083661.78  1754247.81  0.80
1      Decision Tree  3514375.88  2071382.75  0.74
2  Linear Regression  4750043.16  3057311.14  0.53